## **1. Introduction to the Dataset & Business Context**  
About the Dataset and Business Case  

<table align="center" width="100%">
    <tr>
        <td width="35%">
            <img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/398/original/sachin.webp">
        </td>
        <td>
            <div align="center">
                <font color="#e66e82" size="5">
                    <b>Sachin Tendulkar ODI Cricket Career</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Dataset:** <font color="violet">**Sachin Tendulkar ODI Cricket Career**</font> 🏏  
We are analyzing a dataset containing the **ODI (One Day International) cricket stats** of Sachin Tendulkar, one of the greatest cricketers of all time. The dataset provides detailed performance metrics across **360 matches** of his illustrious career. By studying this data, we can explore and gain insights into:  

- **Performance Patterns:** <font color="skyblue">Runs, strike rate, centuries, boundaries</font>, and other key performance indicators.  
- **Match Outcomes:** The relationship between Sachin's performances and the overall outcomes of matches (<font color="green">win or loss</font>).  
- **Opposition & Venue Analysis:** How performance varies against different opponents and at specific grounds.  

**Key Business Objectives:**  
1. <font color="teal">**Understanding Winning Patterns**</font>: Explore how Sachin’s performance influenced match results.  
2. <font color="teal">**Performance Insights**</font>: Identify trends in centuries, strike rates, and boundary contributions.  
3. <font color="teal">**Strategic Scenarios**</font>: Use probability-based analysis to uncover interesting scenarios, such as how often a century correlates with a win.  
4. <font color="teal">**Historical Appreciation**</font>: Showcase Sachin's impact and consistency in ODI cricket with data-driven insights.  

We’ll use this dataset to address a series of probability-related questions, exploring Sachin’s performances across various scenarios. This analysis will demonstrate **data manipulation**, **type conversions**, and **logical operations**.

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv

--2026-06-14 05:40:52--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 3.170.7.158, 3.170.7.168, 3.170.7.32, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|3.170.7.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26440 (26K) [text/plain]
Saving to: ‘Sachin_ODI.csv’

Sachin_ODI.csv      100%[===================>]  25.82K  --.-KB/s    in 0s

2026-06-14 05:40:52 (294 MB/s) - ‘Sachin_ODI.csv’ saved [26440/26440]

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sachin_data  = pd.read_csv("Sachin_ODI.csv")

sachin_data .head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [ ]:
sachin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   runs     360 non-null    int64
 1   NotOut   360 non-null    int64
 2   mins     360 non-null    object
 3   bf       360 non-null    int64
 4   fours    360 non-null    int64
 5   sixes    360 non-null    int64
 6   sr       360 non-null    float64
 7   Inns     360 non-null    int64
 8   Opp      360 non-null    object
 9   Ground   360 non-null    object
 10  Date     360 non-null    object
 11  Winner   360 non-null    object
 12  Won      360 non-null    bool
 13  century  360 non-null    bool
dtypes: bool(2), float64(1), int64(6), object(5)
memory usage: 34.6+ KB



---



## 🎯 <font color="magenta">2. Basic Probability Terminology & Concepts</font>




### 🌟 <font color="skyblue">1. Experiment, Outcomes, and Sample Space</font>

### **Experiment**  
An experiment is any action or process that generates outcomes.  
💡 *Example*: Observing Sachin’s performance in an ODI match is an experiment.

### **Outcome**  
An outcome is a single result of an experiment.  
💡 *Example*: Sachin scoring 100 runs in a specific match is one possible outcome.

### **Sample Space (S)**  
The sample space is the set of all possible outcomes of an experiment.  
💡 *Example*: For Sachin’s ODI career, the sample space might include all possible scores he could achieve in a match (0, 1, 2, ..., 200+).

In [ ]:
## What are all the distinct run totals Sachin Tendulkar has scored in his ODI career, and how many unique outcomes exist?

# Extract unique scores from the dataset
sample_space = sachin_data['runs'].unique()

# Display the sample space
print("Sample Space (Unique Runs):", sorted(sample_space))
print("Number of Unique Outcomes in the Sample Space:", len(sample_space))

Sample Space (Unique Runs): [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(57), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(74), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(104), np.int64(105), np.int64(110), np.int64(111), np.int64(112), np.int64(113), np.int64(114), np.int64(117), np.int64(118), np.int64(120), np.int64(122), np.int64(123), np.int64(124), np.int64(127), np.int64(128), np.int64(134), np.int64(137), np.int64(138), np.int64(139), np.int64(140), np.int64(141), np.int64(143), np.int64(146), np.int64(152), np.int64(163), np.int64(175), np.int64(186), np.int64(200)]
Number of Unique Outcomes in the Sample Space: 122

### Business Context

A sports analytics company wants to understand a player’s scoring patterns to inform commentary, performance predictions, and fan engagement strategies. By analyzing the full range of possible scores a legendary player like Sachin Tendulkar has achieved in ODIs, the company can design statistical models to assess consistency, risk of dismissal, or likelihood of big scores in future scenarios.

### 🌟 <font color="green">2. Events</font>

An event is a subset of the sample space. It can contain one or more outcomes.  
💡 *Example*:  
- **Event A**: Sachin scores more than 100 runs in a match.  
- **Event B**: Sachin scores exactly 0 runs (a duck).

### **Types of Events**

1. **Mutually Exclusive Events**  
   Events that cannot happen at the same time.  
   💡 *Example*: Sachin scoring a century and scoring a duck in the same match.

2. **Joint Events**  
   Events that can happen simultaneously.  
   💡 *Example*: Sachin scores more than 50 runs *and* the match is won by India.

3. **Independent Events**  
   Events where the occurrence of one does not affect the other.  
   💡 *Example*: The outcome of Sachin’s performance and the weather conditions (assuming no match cancellations).

4. **Exhaustive Events**  
   A set of events that covers all possible outcomes in the sample space.  
   💡 *Example*:  
   - Event A: Sachin scores less than 50 runs.  
   - Event B: Sachin scores 50 or more runs.  
   Together, these two events are exhaustive.

### Business Context

A sports analytics firm wants to understand and model different types of player performance scenarios to guide strategic decisions, commentary, and fan engagement. By analyzing events—specific outcomes or combinations of outcomes in Sachin Tendulkar’s ODI career—they can quantify probabilities of critical moments, such as scoring a century, getting out for a duck, or contributing to a team victory.

Understanding mutually exclusive, joint, independent, and exhaustive events helps in:

- Identifying high-impact performance scenarios.

- Designing predictive models for match outcomes.

- Enhancing visual storytelling for fan engagement using set-based visualizations of player performance.

### 🌟 <font color="orange">3. Visualizing Events with Set Operations</font>

Probability often uses **set theory** to describe events. Here are three key operations:

#### <font color="magenta">Intersection (∩)</font>: Matches where both events happen

💡 *Example*: Matches where Sachin scored more than 50 runs *and* India won.

In [ ]:
sachin_data.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [ ]:
## Which ODI matches did Sachin Tendulkar score more than 50 runs and India won, and what were the details of those matches?

# Define events
event_A = sachin_data[sachin_data['runs'] > 50]  # Event A: Scores > 50
event_B = sachin_data[sachin_data['Won'] == True]  # Event B: India wins

# Intersection (A ∩ B)
intersection = pd.merge(event_A, event_B, how='inner')

# Display results
print("Matches where Sachin scored > 50 runs and India won:")
intersection[['Opp', 'Ground', 'runs', 'century', 'Won']]

Matches where Sachin scored > 50 runs and India won:

             Opp     Ground  runs  century   Won
0      Sri Lanka    Sharjah   112     True  True
1          Kenya    Cuttack   127     True  True
2    West Indies    Gwalior    70    False  True
3       Pakistan    Sharjah   118     True  True
4       Pakistan    Toronto    89    False  True
..           ...        ...   ...      ...   ...
68     Sri Lanka    Cuttack    96    False  True
69  South Africa    Gwalior   200     True  True
70     Australia  Ahmedabad    53    False  True
71      Pakistan     Mohali    85    False  True
72      Pakistan      Dhaka    52    False  True

[73 rows x 5 columns]

In [ ]:
intersection["runs"].min(), intersection["Won"].unique()

(52, array([ True]))

In [ ]:
intersection.shape[0] # favourable outcomes

73

In [ ]:
sachin_data.shape[0] # Total Matches (Outcomes)

360

In [ ]:
np.round(intersection.shape[0] / sachin_data.shape[0], 4)

np.float64(0.2028)

In [ ]:
# event_A, event_A
event_A.head()

# P(event_A) = event_A.shape[0] / sachin_data.shape[0]
# event_A.shape[0] = number of fav events
#  sachin_data.shape[0] = total number of events
P_event_A = event_A.shape[0] / sachin_data.shape[0]
P_event_B = event_B.shape[0] / sachin_data.shape[0]

# print(P_event_A, P_event_B)

# P(A and B) = P(A) * P(B), when A and B are independent
print(P_event_A * P_event_B)

0.1689506172839506

In [ ]:
# P_event_A * P_event_B ! = intersection.shape[0] / sachin_data.shape[0] ; This could suggest, that the events not be independent.

### Business Context

A cricket analytics company wants to identify high-impact matches where a player’s performance directly contributes to team success. By analyzing intersections of events—such as Sachin Tendulkar scoring more than 50 runs and India winning—the company can:

- Highlight matches where Sachin’s performance was pivotal.

- Quantify the correlation between individual contributions and team victories.

- Provide insights for commentators, performance analysts, and fan engagement content.

#### <font color="skyblue">Union (∪)</font>: Matches where either event happens

💡 *Example*: Matches where Sachin scored more than 50 runs *or* India won.

In [ ]:
## List all ODI matches where either Sachin Tendulkar scored more than 50 runs or India won, along with the match details
# Union (A ∪ B) using concatenation and dropping duplicates
union = pd.concat([event_A, event_B]).drop_duplicates()

# Display results
print("Matches where Sachin scored > 50 runs or India won:")
union[['Opp', 'Ground', 'runs', 'century']]

Matches where Sachin scored > 50 runs or India won:

             Opp   Ground  runs  century
5      Sri Lanka  Sharjah   112     True
10   New Zealand   Nagpur    65    False
12         Kenya  Cuttack   127     True
13   West Indies  Gwalior    70    False
14     Australia   Mumbai    90    False
..           ...      ...   ...      ...
346  West Indies  Chennai     2    False
349    Sri Lanka   Mumbai    18    False
351    Sri Lanka    Perth    48    False
356    Sri Lanka   Hobart    39    False
357    Sri Lanka    Dhaka     6    False

[230 rows x 4 columns]

In [ ]:
union.shape[0] / sachin_data.shape[0]

0.6388888888888888

### Business Context

A sports analytics team wants to identify all impactful matches, either driven by Sachin Tendulkar’s strong performance or by team success. By analyzing the union of events—matches where Sachin scored more than 50 runs or India won—they can:

- Capture a broader set of influential matches for commentary and fan engagement.

- Understand both individual brilliance and team performance.

- Identify matches worth highlighting in performance summaries or predictive models.

#### <font color="green">Complement (A')</font>: Matches where the event does not happen

💡 *Example*: Matches where Sachin did **not** score a century.

In [ ]:
# Which ODI matches did Sachin Tendulkar not score a century, and what are the details of those matches?
# Complement (A'): Matches where Sachin did not score a century
event_A_complement = sachin_data[sachin_data['runs'] < 100]  # Not a century
# event_A_complement = sachin_data[sachin_data['century'] == False]

# Display results
print("Matches where Sachin did not score a century:")
event_A_complement[['Opp', 'Ground', 'runs', 'century']]

Matches where Sachin did not score a century:

              Opp    Ground  runs  century
0     New Zealand    Napier    13    False
1    South Africa  Hamilton    37    False
2       Australia   Dunedin    47    False
3      Bangladesh   Sharjah    48    False
4        Pakistan   Sharjah     4    False
..            ...       ...   ...      ...
354     Sri Lanka  Brisbane    22    False
355     Australia    Sydney    14    False
356     Sri Lanka    Hobart    39    False
357     Sri Lanka     Dhaka     6    False
359      Pakistan     Dhaka    52    False

[314 rows x 4 columns]

### Business Context

A cricket analytics team wants to study matches where Sachin Tendulkar did not achieve a milestone, such as a century, to:

- Understand patterns in games where he performed below peak levels.

- Analyze factors that might have influenced lower scores (opposition, venue, match conditions).

- Provide insights for performance improvement strategies, commentary, or predictive modeling.



---
## 🎯 <font color="magenta">3. Probability Rules</font>

Understanding the fundamental rules of probability helps us compute the likelihood of events systematically. Let’s explore these rules using **Sachin Tendulkar’s ODI career data**.

### 🌟 <font color="skyblue">1. Addition Rule</font>

The addition rule calculates the probability of either one event or another happening (union of events).

**Formula:**

$
P(A \cup B) = P(A) + P(B) - P(A \cap B)
$

💡 **Example:**

What is the probability that Sachin scored more than 50 runs (Event A) **or** India won the match (Event B)?

In [ ]:
# What is the probability that Sachin Tendulkar scored more than 50 runs or India won the match in his ODI career?

# Total matches
total_matches = len(sachin_data) # sachin_data.shape[0]

# Event A: Sachin scored > 50 runs
event_A = sachin_data[sachin_data['runs'] > 50]

# Event B: India won the match
event_B = sachin_data[sachin_data['Won'] == True]

# Intersection (A ∩ B): Matches where Sachin scored > 50 runs and India won
intersection = pd.merge(event_A, event_B, how='inner')

# Probabilities
P_A = len(event_A) / total_matches
P_B = len(event_B) / total_matches
P_A_intersection_B = len(intersection) / total_matches

# Applying the addition rule
P_A_union_B = P_A + P_B - P_A_intersection_B # P(A) + P(B) - P(A intersection B)

print(f"Probability of scoring > 50 runs or India winning: {P_A_union_B:.4f}")

Probability of scoring > 50 runs or India winning: 0.6727

### Business Context

A sports analytics company wants to quantify the likelihood of key match outcomes involving Sachin Tendulkar’s performance and team success. By calculating probabilities using the addition rule, they can:

- Determine how often Sachin scores above 50 or India wins, helping assess his impact on match outcomes.

- Inform predictive models for match results based on player performance.

- Provide statisticians, commentators, and fans with data-driven insights on performance scenarios.

### 🌟 <font color="green">2. Multiplication Rule</font>

The multiplication rule calculates the probability of both events happening (intersection of events).

**Formula:**  

$
P(A \cap B) = P(A) \cdot P(B \mid A)
$

💡 **Example:**

What is the probability that Sachin scored more than 50 runs (Event A) **and** India won the match (Event B)?

The probability of India winning depends on whether Sachin scores more than 50 runs.

We cannot directly calculate the joint probability
𝑃
(
𝐴
∩
𝐵
)
 without knowing
𝑃
(
𝐵
∣
𝐴
)(the probability of India winning given Sachin's performance).

Without the formula, we'd have to experimentally determine how often India wins when Sachin scores more than 50, which is impractical with real-world data.

In [ ]:
sachin_data

# What is the probability that Sachin Tendulkar scored more than 50 runs and India won the match in his ODI career?

# Given that sachin has scored > 50 runs, what are the chances that India Wins

# 1. Filter out rows where sachin > 50 runs (first condition)
conditional_data = sachin_data[sachin_data["runs"] > 50]
conditional_data

# 2. Out of the conditional data, take out rows where India won
india_won = conditional_data[conditional_data["Won"] == True]

# 3. Find the probability P(B|A) = india_won_matches / sachin scored > 50
P_B_given_A = len(india_won) / len(conditional_data)
P_B_given_A

0.6134453781512605

In [ ]:
## What is the probability that Sachin Tendulkar scored more than 50 runs and India won the match in his ODI career?
# Event A: Sachin scored > 50 runs
P_A = len(event_A) / total_matches

# Conditional probability: P(B | A)
conditional_data = sachin_data[sachin_data['runs'] > 50] # Filtered data, based on first condition (sachin > 50 runs)
P_B_given_A = len(conditional_data[conditional_data['Won'] == True]) / len(event_A) # P(B|A)

# Applying the multiplication rule # P(A and B) = P(A) * P(B | A)
P_A_intersection_B = P_A * P_B_given_A

print(f"Probability of scoring > 50 runs and India winning: {P_A_intersection_B:.4f}")

Probability of scoring > 50 runs and India winning: 0.2028

### Business Context

A cricket analytics team wants to measure the likelihood of joint outcomes involving Sachin Tendulkar’s performance and team success. By applying the multiplication rule, they can:

Determine the probability that Sachin scores more than 50 and India wins, capturing the combined effect of player performance on match results.

Inform predictive modeling for match strategies, player impact analysis, and commentary insights.

Avoid impractical manual counting of joint occurrences across hundreds of matches by using conditional probabilities.

### 🌟 <font color="orange">3. Marginal vs. Joint Probability</font>

- **Marginal Probability**: Probability of a single event happening (e.g., P(A) or P(B)).  
  💡 *Example*: Probability that Sachin scored a century (Event C).  

- **Joint Probability**: Probability of two events happening together (e.g., P(A ∩ B)).  
  💡 *Example*: Probability that Sachin scored more than 50 runs **and** hit at least one six (Event D).

1️⃣ When We Can Directly Calculate Joint Probability
We can directly compute
𝑃
(
𝐴
∩
𝐵
)
P(A∩B) when we have historical data or independent events.

✅ Example: Rolling Two Dice (Independent Events)
Let A = Getting a 4 on the first die.

Let B = Getting a 6 on the second die.

Since rolling one die does not affect the other, the events are independent:

𝑃
(
𝐴
∩
𝐵
)
=
𝑃
(
𝐴
)
×
𝑃
(
𝐵
)
=
1
6
×
1
6
=
1
36


👉 Here, we can directly multiply because the events are independent.

2️⃣ When We Cannot Directly Calculate Joint Probability
If events are dependent, we need extra information about how they influence each other.

❌ Example: Sachin Scoring & India Winning (Dependent Events)
If Sachin scores more than 50 runs (A), it increases the chance of India winning (B).

Here, we do not have
𝑃
(
𝐴
∩
𝐵
)
 directly.

Instead, we have:

𝑃
(
𝐴
∩
𝐵
)
=
𝑃
(
𝐴
)
×
𝑃
(
𝐵
∣
𝐴
)
👉 We need conditional probability because one event affects the other.

In [ ]:
#What is the marginal probability that Sachin Tendulkar scored a century, and what is the joint probability
# that he scored more than 50 runs and hit at least one six in an ODI match?

# Marginal probability: Sachin scored a century
event_C = sachin_data[sachin_data['century'] == True] # Century = True
P_C = len(event_C) / total_matches

# Joint probability: Sachin scored > 50 runs and hit at least 1 six
event_D = sachin_data[(sachin_data['runs'] > 50) & (sachin_data['sixes'] > 0)]
P_D = len(event_D) / total_matches

print(f"Marginal Probability of Sachin scoring a century: {P_C:.4f}")
print(f"Joint Probability of scoring > 50 runs and hitting at least 1 six: {P_D:.4f}")

Marginal Probability of Sachin scoring a century: 0.1278
Joint Probability of scoring > 50 runs and hitting at least 1 six: 0.1889

In [ ]:
sachin_data.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [ ]:
# 1. Find the marginal probablity where Sachin scores a 0
sachin_zero = sachin_data[sachin_data["runs"] == 0]
p_zero = len(sachin_zero) / total_matches
print(f"Marginal Probability of Sachin scoring 0 runs: {p_zero:.4f}")

# 2. Find the probability where Sachin had a sr < 100 and india lost the match.
sr_less_than_100 = sachin_data[sachin_data['sr'] < 100]
india_lost = sachin_data[sachin_data["Won"] == False]

# 3. Merge the two
df = pd.merge(sr_less_than_100, india_lost, how="inner")
ans = len(df) / total_matches
print(f"Probability where Sachin had a sr < 100 and india lost the match: {ans: .4f}")

Marginal Probability of Sachin scoring 0 runs: 0.0389
Probability where Sachin had a sr < 100 and india lost the match:  0.3917

### Business Context

A cricket analytics firm wants to differentiate between single-event probabilities and combined-event probabilities in player performance:

- Marginal probability helps understand the likelihood of individual milestones, e.g., how often Sachin scores a century.

- Joint probability measures the chance of multiple achievements occurring together, e.g., scoring over 50 runs and hitting at least one six.

This analysis is crucial for:

- Performance modeling and predictive analytics.

- Evaluating player consistency and impact in high-stakes situations.

- Designing metrics for commentary, fan engagement, or fantasy cricket platforms.

### 🌟 <font color="purple">4. Conditional Probability</font>

Conditional probability calculates the likelihood of an event given that another event has already occurred.

**Formula:**  

$
P(B \mid A) = \frac{P(A \cap B)}{P(A)}
$

💡 **Example:**  

Given that Sachin scored more than 50 runs (Event A), what is the probability that he scored a century (Event C)?

In [ ]:
## Given that Sachin Tendulkar scored more than 50 runs in an ODI match, what is the probability that he went on to score a century?

# Event A: Sachin scored > 50 runs
event_A = sachin_data[sachin_data['runs'] > 50]

# Event C: Sachin scored a century
event_C_given_A = event_A[event_A['century'] == True]

# Conditional probability
P_C_given_A = len(event_C_given_A) / len(event_A)

print(f"Probability of scoring a century given runs > 50: {P_C_given_A:.4f}")

Probability of scoring a century given runs > 50: 0.3866

### Business Context

A cricket analytics team wants to evaluate the likelihood of milestone achievements given a prior performance. By calculating conditional probabilities, they can:

- Assess the probability that Sachin Tendulkar scored a century given he had already scored more than 50 runs in a match.

- Identify scenarios where high scores are likely to convert into major milestones.

- Inform predictive models, commentary insights, and performance strategy evaluations.



---

## 🎯 <font color="magenta">4. Bayes' Theorem</font>

Bayes' Theorem is a cornerstone of probability theory that helps us revise probabilities based on new evidence. It enables us to calculate **conditional probabilities** when the reverse probability and other relevant information are known.

### 🌟 <font color="skyblue">1. Formula for Bayes' Theorem</font>

The formula for Bayes' Theorem is:  
$
P(A \mid B) = \frac{P(B \mid A) \cdot P(A)}{P(B)}
$

Where:  
- $ P(A \mid B) $: Probability of $ A $ occurring given that $ B $ has occurred (posterior).  
- $ P(B \mid A) $: Probability of $ B $ occurring given that $ A $ has occurred (likelihood).  
- $ P(A) $: Probability of $ A $ occurring (prior).  
- $ P(B) $: Probability of $ B $ occurring (evidence).

### 🌟 <font color="green">2. Intuition Behind Bayes' Theorem</font>

💡 **Example:**  
In Sachin’s dataset:
- Event $ A $: Sachin scores a century.  
- Event $ B $: Sachin batted first.

We want to compute $ P(A \mid B) $:  
> *What is the probability that Sachin scores a century given he batted first?*

In [ ]:
## Given that Sachin Tendulkar batted first in an ODI match, what is the probability that he scored a century?

# Define the events
event_A = sachin_data[sachin_data['century'] == True]  # Event A: Scored a century
event_B = sachin_data[sachin_data['Inns'] == 1]        # Event B: Batted first

# Total matches
total_matches = len(sachin_data)

# Probabilities
P_A = len(event_A) / total_matches  # Prior probability of scoring a century # P(A)
P_B = len(event_B) / total_matches  # Probability of batting first # P(B)
P_B_given_A = len(event_A[event_A['Inns'] == 1]) / len(event_A)  # Likelihood # P(B | A)

# Bayes' Theorem
P_A_given_B = (P_B_given_A * P_A) / P_B # (P(A) * P(B|A) / P(B))

print(f"Probability of scoring a century given Sachin batted first: {P_A_given_B:.4f}")

Probability of scoring a century given Sachin batted first: 0.1765

In [ ]:
## Given that Sachin Tendulkar batted did not first in an ODI match, what is the probability that he scored a century?

# Define the events
event_A = sachin_data[sachin_data['century'] == True]  # Event A: Scored a century
event_B = sachin_data[sachin_data['Inns'] != 1]        # Event B: Not Batted first

# Total matches
total_matches = len(sachin_data)

# Probabilities
P_A = len(event_A) / total_matches  # Prior probability of scoring a century
P_B = len(event_B) / total_matches  # Probability of not batting first
P_B_given_A = len(event_A[event_A['Inns'] != 1]) / len(event_A)  # Likelihood

# Bayes' Theorem
P_A_given_B = (P_B_given_A * P_A) / P_B

print(f"Probability of scoring a century given Sachin did not batted first: {P_A_given_B:.4f}")

Probability of scoring a century given Sachin did not batted first: 0.0842

### Business Context

A cricket analytics team wants to revise probabilities based on new information to gain deeper insights into player performance. By applying Bayes’ Theorem, they can:

- Compute the probability that Sachin Tendulkar scores a century given he batted first, updating prior expectations based on observed match conditions.

- Understand how match circumstances (like batting order) influence milestone achievements.

- Support predictive modeling, strategy analysis, and commentary by incorporating conditional insights.

Bayes’ Theorem allows the team to combine historical performance data with contextual information for more accurate probability estimates.

### 🌟 <font color="purple">4. Real-Life Relevance</font>

Bayes' Theorem is widely used in:
- **Spam Detection**: Classifying emails as spam or not based on keywords.  
- **Medical Testing**: Revising the probability of having a disease based on test results.  
- **Sports Analytics**: Understanding player performance under specific conditions.

### 🌟 <font color="skyblue">5. Simple Tree Diagram Approach (Optional)</font>

A **tree diagram** can help visualize the probabilities involved in Bayes' Theorem.

💡 **Example**: Using Tree Diagram Data for Complex Joint Probabilities  

What is the probability of **Sachin scoring between 50-100 runs** and **India winning**, considering the batting order?

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/404/original/Screenshot_2024-12-30_113248.png)

---

### <font color="purple">6. `pd.concat` Function Example</font>

The `pd.concat` function in pandas is used to concatenate pandas objects along a particular axis. It's particularly useful for combining DataFrames or Series.

In [ ]:
import pandas as pd

# Create two sample DataFrames
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})

print("DataFrame 1:")
display(df1)

print("\nDataFrame 2:")
display(df2)

# Concatenate them along rows (default axis=0)
result_rows = pd.concat([df1, df2])
print("\nConcatenated along rows (default):")
display(result_rows)

# Concatenate them along columns (axis=1)
result_cols = pd.concat([df1, df2], axis=1)
print("\nConcatenated along columns:")
display(result_cols)

DataFrame 1:

    A   B
0  A0  B0
1  A1  B1

DataFrame 2:

    A   B
0  A2  B2
1  A3  B3

Concatenated along rows (default):

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

Concatenated along columns:

    A   B   A   B
0  A0  B0  A2  B2
1  A1  B1  A3  B3